### ISSUE TITLE
Build failed on macOS

### ISSUE THREAD

**Issue by leizongmin** [theanarkh/Deer#1]
I try to run `make` on macOS, got the following errors:

```
2 warnings generated.
ld: warning: directory not found for option '-Lyour_path_for_v8_lib/'
ld: library not found for -lv8_monolith
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [run] Error 1
```

I seems that the `your_path_for_v8_lib` directory is missing. Is there documentation on how to get this directory contents?

**Comment by sunchencc** [comment]
挂机  出去玩O(∩_∩)O

**Comment by theanarkh** [comment]
I have added a script file (`install.sh`) to build V8 and Deer. But it may fail because of the network. In addition, this article(https://zhuanlan.zhihu.com/p/404751211) may be helpful .

**Comment by cd-yang** [comment]
I got the following error while I can access `googleapis.com`

> <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
Retrying in 5 s ...
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac_arm64/clang-llvmorg-16-init-6084-g2f3d7c2c-1.tar.xz 
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
Retrying in 10 s ...
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac_arm64/clang-llvmorg-16-init-6084-g2f3d7c2c-1.tar.xz 
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
Retrying in 20 s ...
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac_arm64/clang-llvmorg-16-init-6084-g2f3d7c2c-1.tar.xz 
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
Failed to download prebuilt clang package clang-llvmorg-16-init-6084-g2f3d7c2c-1.tar.xz
Use build.py if you want to build locally.
Exiting.

 
Maybe it's due to python
I am using Python 3.8.10 on macOS 12.2.1.

**Comment by cd-yang** [comment]
> I got the following error while I can access `googleapis.com`

Solved this cert problem by installing the "Install Certificates.command"
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

But ran into another error 😭 

> ________ running 'python3 tools/clang/scripts/update.py' in '/Users/cdyang/Documents/VSCodeRepos/Deer/deps/v8'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac_arm64/clang-llvmorg-16-init-6084-g2f3d7c2c-1.tar.xz .......... Done.
Hook 'vpython3 -vpython-spec .vpython3 -vpython-tool install' took 11.59 secs
Running hooks: 100% (30/30), done.                  
Hint: You can raise verbosity (-vv) to see the output of failed commands.
Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 309, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 303, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 162, in cmd_gen
    self._call_cmd([
  File "tools/dev/v8gen.py", line 211, in _call_cmd
    output = subprocess.check_output(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.8/bin/python3', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release.sample', 'out.gn/x64.release.sample']' returned non-zero exit status 1.
ninja: Entering directory `out.gn/x64.release.sample'
ninja: error: loading 'build.ninja': No such file or directory
g++ -g -Ideps/v8/include Deer.cc core/*.cc -o Deer -lv8_monolith -ldl -Ldeps/v8/out.gn/x64.release.sample/obj -pthread -std=c++17 -DV8_COMPRESS_POINTERS -DV8_ENABLE_SANDBOX

**Comment by theanarkh** [comment]
Yes, me too. Finally, download successfully. Maybe you can find the v8 static library on github.

**Comment by leizongmin** [comment]
A little modification to `build.sh` and `install.sh` might be more user friendly:

```diff
+ set -e

cd deps/v8 && tools/dev/v8gen.py x64.release.sample
../depot_tools/ninja -C out.gn/x64.release.sample v8_monolith
cd ../.. && make && ./Deer test/tcp/server.js
```

**Comment by theanarkh** [comment]
Thanks, I'll update later.

**Comment by leizongmin** [comment]
V8 has been successfully compiled, but there is still an error when linking `Deer`:

```
ld: library not found for -lv8_monolith
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [run] Error 1
```

The static library file `./deps/v8/out.gn/x64.release.sample/obj/libv8_monolith.a` is exists. Other dependent libraries have the same problem.

Finally I solved the problem by adding the following flags to the `g++` command:

```
-Ldeps/v8/out.gn/x64.release.sample/obj -Ldeps/llhttp/build
```

**Comment by leizongmin** [comment]
Still have issues on macOS, maybe `llhttp` needs static linking:

```
dyld[73663]: Library not loaded: 'build/libllhttp.so'
  Referenced from: '/Users/bytedance/github/others/Deer/Deer'
  Reason: tried: 'build/libllhttp.so' (no such file), '/usr/local/lib/libllhttp.so' (no such file), '/usr/lib/libllhttp.so' (no such file)
fish: Job 1, './Deer' terminated by signal SIGABRT (Abort)
```

**Comment by theanarkh** [comment]
The `install.sh` will copy `libllhttp.a` and `libv8_monolith.a` to `lib` dir. then compile `Deer` by `g++ -g -Ideps/v8/include -Ideps/llhttp/build Deer.cc core/*.cc -o Deer -lv8_monolith -ldl -lllhttp -Llib -pthread -std=c++17 -DV8_COMPRESS_POINTERS -DV8_ENABLE_SANDBOX`. It works on my PC.
